// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    HomePageBanner: typeof import('./src/components/HomePage/Banner.vue')['default']
    HomePageButtonBox: typeof import('./src/components/HomePage/ButtonBox.vue')['default']
    HomePageHoverBox: typeof import('./src/components/HomePage/HoverBox.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
